### ISSUE TITLE
Can't use the demo , file permission errrors

### ISSUE THREAD

**Issue by Jerczey** [keycloak/keycloak-demo#2]
Hello!

First of all, thanks for the keycloak project!
and thanks for this demo... but I can't make it work on CDK version 3.5

[jerczey@yurek-fedora CDK]$ ./minishift version
minishift v1.20.0+1bd6d5c
CDK v3.5.0-1

[jerczey@yurek-fedora CDK]$ ./minishift openshift version
openshift v3.9.31
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16

This is the error log for the pod unable to read the file permissions, 
is it me ?
or could the docker image have problems between root and jboss (?) user when accessing the deployment?

Also, does keycloak uses the PBKDF2 algorithm ? it might need them cipher suites perhaps?

Thanks! 

LOG:
java.lang.RuntimeException: PBKDF2 algorithm not found
=========================================================================
  Using Embedded H2 database
=========================================================================
=========================================================================
  JBoss Bootstrap Environment
  JBOSS_HOME: /opt/jboss/keycloak
  JAVA: /usr/lib/jvm/java/bin/java
  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
=========================================================================
15:15:49,266 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
15:15:49,725 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
15:15:49,921 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: WildFly Core 3.0.8.Final "Kenny" starting
15:15:49,990 INFO  [org.jboss.vfs] (MSC service thread 1-4) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
15:15:51,958 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:15:51,994 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 21) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:15:52,020 INFO  [org.wildfly.security] (ServerService Thread Pool -- 5) ELY00001: WildFly Elytron version 1.1.6.Final
15:15:52,085 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 23) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "keycloak-server")]): java.lang.NullPointerException
	at org.keycloak.subsystem.server.extension.ServerUtil.findServerWarUri(ServerUtil.java:77)
	at org.keycloak.subsystem.server.extension.ServerUtil.<init>(ServerUtil.java:63)
	at org.keycloak.subsystem.server.extension.KeycloakSubsystemAdd.populateModel(KeycloakSubsystemAdd.java:90)
	at org.jboss.as.controller.AbstractAddStepHandler.execute(AbstractAddStepHandler.java:145) [wildfly-controller-3.0.8.Final.jar:3.0.8.Final]
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:980) [wildfly-controller-3.0.8.Final.jar:3.0.8.Final]
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:726) [wildfly-controller-3.0.8.Final.jar:3.0.8.Final]
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:450) [wildfly-controller-3.0.8.Final.jar:3.0.8.Final]
	at org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:386) [wildfly-controller-3.0.8.Final.jar:3.0.8.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_161]
	at org.jboss.threads.JBossThread.run(JBossThread.java:320) [jboss-threads-2.2.1.Final.jar:2.2.1.Final]
15:15:52,118 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0017: Initial deployment scan failed: java.lang.RuntimeException: WFLYDS0032: Failed to list files in directory /opt/jboss/keycloak/standalone/deployments. Check that the contents of the directory are readable.
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.listDirectoryChildren(FileSystemDeploymentService.java:1351) [wildfly-deployment-scanner-3.0.8.Final.jar:3.0.8.Final]
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.establishDeployedContentList(FileSystemDeploymentService.java:435) [wildfly-deployment-scanner-3.0.8.Final.jar:3.0.8.Final]
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.bootTimeScan(FileSystemDeploymentService.java:470) [wildfly-deployment-scanner-3.0.8.Final.jar:3.0.8.Final]
	at org.jboss.as.server.deployment.scanner.DeploymentScannerAdd$2.run(DeploymentScannerAdd.java:160) [wildfly-deployment-scanner-3.0.8.Final.jar:3.0.8.Final]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [rt.jar:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_161]
	at org.jboss.threads.JBossThread.run(JBossThread.java:320) [jboss-threads-2.2.1.Final.jar:2.2.1.Final]
Caused by: java.nio.file.AccessDeniedException: /opt/jboss/keycloak/standalone/deployments
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) [rt.jar:1.8.0_161]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) [rt.jar:1.8.0_161]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) [rt.jar:1.8.0_161]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) [rt.jar:1.8.0_161]
	at java.nio.file.Files.newDirectoryStream(Files.java:457) [rt.jar:1.8.0_161]
	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.listDirectoryChildren(FileSystemDeploymentService.java:1346) [wildfly-deployment-scanner-3.0.8.Final.jar:3.0.8.Final]
	... 11 more
15:15:52,299 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) "WFLYCTL0193: Failed executing subsystem keycloak-server boot operations"
15:15:52,301 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("parallel-subsystem-boot") failed - address: ([]) - failure description: "\"WFLYCTL0193: Failed executing subsystem keycloak-server boot operations\""
15:15:52,314 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
15:15:52,380 INFO  [org.jboss.as] (MSC service thread 1-4) WFLYSRV0050: WildFly Core 3.0.8.Final "Kenny" stopped in 37ms

**Comment by stianst** [comment]
I've not tried it on CDK. I'm using plain Docker distribution on Fedora with MiniShift.

Not sure what's going on here, but perhaps it's some sort of file permissions or perhaps some SE linux stuff. It seems it can't find the files needed and my only thoughts there is that it doesn't have permissions to read them or something like that.
